name: S3 Demo Packaging
on: [push, workflow_dispatch]
jobs:
  Build-Package-Workspace-Starter-S3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} / ${{steps.extract_branch.outputs.branch}} and your repository is ${{ github.cd  }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run package-how-tos-s3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Deploy ğŸš€
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'public-s3'      # optional: defaults to entire repository
          DEST_DIR: workspace-starter